# Enforces the update of a changelog file on every pull request
# Can be skipped with the `Skip Changelog` label
name: Changelog Update Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: dangoslen/changelog-enforcer@v3
      with:
        skipLabels: 'Skip Changelog'
