name: Repo checks

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --color=yes --project=scripts/ -e 'using Pkg; Pkg.instantiate()'
      - name: Test scripts/changelog.jl
        run: |
          julia --color=yes --project=scripts/ scripts/changelog.jl test
          julia --color=yes --project=scripts/ scripts/changelog.jl --file=scripts/changelog-valid.md
          ! julia --color=yes --project=scripts/ scripts/changelog.jl --file=scripts/changelog-invalid.md
      - name: Check CHANGELOG.md
        run: julia --color=yes --project=scripts/ scripts/changelog.jl --github
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
