name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: 3
permissions:
  contents: write
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          changelog: |
            {% if custom %}
            {{ custom }}
            {% endif %}

            The changes are documented in the [`CHANGELOG.md`](https://github.com/JuliaDocs/Documenter.jl/blob/{{ version }}/CHANGELOG.md) file.

            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
